package com.cg.customer.entity;

public enum status {
	PENDING, APPROVED, WAITING_FOR_FINANCE_APPROVAL, WAITING_FOR_LAND_VERIFICATION_APPROVAL, REJECTED,
	DOCUMENTS_NOT_UPLOADED, DOCUMENTS_UPLOADED;

}
